name = "hammal"
type = "webpack"
account_id = "33f0fd43ecb3be2c4401478926a55d14"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "329223fe7f2f484098a2b9c3e9dc78a7" }
]
